# Generated by Django 5.1.6 on 2025-04-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
